if (MSVC)
function(assign_source_group)
    foreach(_source IN ITEMS ${ARGN})	
		if(_source MATCHES "ui_.*" OR _source MATCHES "moc_.*" OR _source MATCHES "qrc_.*" OR _source MATCHES ".*cpp.rule")
			source_group("moc" FILES "${_source}")
		#ui文件
		elseif(_source MATCHES ".*.ui" OR _source MATCHES ".*.qrc")
			source_group("src\\moc" FILES "${_source}")
		else()
			if (IS_ABSOLUTE "${_source}")
				file(RELATIVE_PATH _source_rel "${CMAKE_CURRENT_SOURCE_DIR}" "${_source}")
			else()
				set(_source_rel "${_source}")
			endif()
			get_filename_component(_source_path "${_source_rel}" PATH)
			string(REPLACE "/" "\\" _source_path_msvc "${_source_path}")
			source_group("src\\${_source_path_msvc}" FILES "${_source}")
		endif()   
    endforeach()
endfunction(assign_source_group)

function(my_add_executable first_arg)
	#第一个参数不处理
    foreach(_source IN ITEMS ${ARGN})
        assign_source_group(${_source})
    endforeach()
    add_executable(${ARGV})
endfunction(my_add_executable)

endif (MSVC)