#不设置，windows下动态库不会生成.lib文件
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)

if(CMAKE_BUILD_TYPE  MATCHES "Debug")
SET(BIN_DIR_DEBUG ${CMAKE_SOURCE_DIR}/output/bin_d)  
SET(BIN_DIR ${CMAKE_SOURCE_DIR}/output/bin_d)  
else() 
SET(BIN_DIR_RELEASE ${CMAKE_SOURCE_DIR}/output/bin)
SET(BIN_DIR ${CMAKE_SOURCE_DIR}/output/bin)  
endif()

set(CMAKE_CXX_STANDARD 17)

#设置库文件输出目录
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG  	${BIN_DIR_DEBUG})		#设置lib目录
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE  ${BIN_DIR_RELEASE})		#设置lib目录
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG	${BIN_DIR_DEBUG})		#设置dll目录
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE	${BIN_DIR_RELEASE})		#设置dll目录
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG 	${BIN_DIR_DEBUG})		#设置exe目录
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE 	${BIN_DIR_RELEASE})		#设置exe目录

