#不设置，windows下动态库不会生成.lib文件
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
set(CMAKE_DEBUG_POSTFIX "_d") 

set(CMAKE_CXX_STANDARD 17)

#设置库文件输出目录
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG  	${CMAKE_SOURCE_DIR}/output/bin)		#设置lib目录
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE  ${CMAKE_SOURCE_DIR}/output/bin)		#设置lib目录
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG	${CMAKE_SOURCE_DIR}/output/bin)		#设置dll目录
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE	${CMAKE_SOURCE_DIR}/output/bin)		#设置dll目录
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG 	${CMAKE_SOURCE_DIR}/output/bin)		#设置exe目录
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE 	${CMAKE_SOURCE_DIR}/output/bin)		#设置exe目录

